apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SzaDav188/Apps.git
    targetRevision: HEAD
    path: gitlab/gitlab
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab


## error log

Unable to create application: application spec for gitlab is invalid: 
InvalidSpecError: Unable to generate manifests in gitlab/gitlab: 
rpc error: code = Unknown desc = failed to execute helm template command: 
failed to get command args to log: `helm template . --name-template gitlab --namespace gitlab --kube-version 1.34 <api versions removed> --include-crds` failed exit status 1: 
Error: execution error at (gitlab/charts/certmanager-issuer/templates/cert-manager.yml:14:3): You must provide an email to associate with your TLS certificates. 
Please set certmanager-issuer.email Use --debug flag to render out invalid YAML